### PR TITLE
Add Espressif ESP32-S3-DevKitC-1-N16R8V board file

### PR DESCRIPTION
**Pull request by handledexception**
Tested with PlatformIO 2.5.4 in VSCode with a TTGO T-Display-S3 16MB version.

Should resolve https://github.com/platformio/platform-espressif32/issues/915

### CODE REVIEW

**Comment by handledexception** [comment]
Any chance this will get merged?

**Comment by valeros** [comment]
Hi @handledexception, thanks for the PR. IMO, there is no reason to create yet another manifest with minimal changes for a board that's already available. It can be easily configured directly from the project configuration file.

**Comment by handledexception** [comment]
> Hi @handledexception, thanks for the PR. IMO, there is no reason to create yet another manifest with minimal changes for a board that's already available. It can be easily configured directly from the project configuration file.

OK, thank you. I didn't realize that was the intended workflow.

**Comment by FreeFrags** [comment]
@handledexception i just purchased a TTGO T-Display-S3 too and because i couldnt find it in the boards list i created #975.

Did i understand correctly that this issue was closed because we can use a different board and override some properties? 

would you mind telling us how we could get started with the board? im sorry its my first board and im trying to get familiar with the basics

**Comment by handledexception** [comment]
I have no idea what the intended workflow should be to use PlatformIO with the T-Display-S3, hence why I made the PR to add that board file. If there is a workflow that the PlatformIO maintainers intend I would love to hear it. I've just continued using the board file from this PR in my own work and moved on.

**Review by thhkd — COMMENTED** [review]
Tested in 6.1.11. Worked as expected.

**Comment by rgov** [comment]
> **@valeros:** It can be easily configured directly from the project configuration file.

Would you mind explaining how?

**Comment by valeros** [comment]
@rgov for example:
```ini
[env:esp32-s3-devkitc-1]
platform = espressif32
framework = arduino
board = esp32-s3-devkitc-1

# Configure options for the N16R8V variant
build_flags= -DBOARD_HAS_PSRAM
board_build.arduino.memory_type = qio_opi 
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
```

**Comment by hsetlik** [comment]
Great! Is there a property for specifying the PSRAM size?

**Comment by rgov** [comment]
> Great! Is there a property for specifying the PSRAM size?

I don't believe you have to. I believe the build option just tells the Arduino initialization code to call [`psramInit()`](https://github.com/espressif/arduino-esp32/blob/ccacb7e3d1dd0e58b309c83e5ebc2302ce97c7b2/cores/esp32/esp32-hal-psram.c#L44) which invokes the ESP-IDF function [`esp_psram_init()`](https://github.com/espressif/esp-idf/blob/5f4249357372f209fdd57288265741aaba21a2b1/components/esp_psram/esp_psram.c#L106). Somewhere in there it sends a `PSRAM_DEVICE_ID` command over SPI and uses the reply to determine the PSRAM size.

**Pull request closed without merging**
