### PR TITLE
feat: Try to use kconfiglib to do menuconfig.

### PR DESCRIPTION
**Pull request by GeneKong**
For windows, it's better to use kconfiglib to do menuconfig instead default tools.
Please check and try to update.

### CODE REVIEW

**Comment by valeros** [comment]
Hi @GeneKong ! Thanks for the PR. Could you please explain what are exactly the benefits of using `kconfiglib` directly? To minimize the chance of possible issues, we tend to use the same tools as the original framework as much as possible. In case when the maintainers of `ESP-IDF` decide to switch to a new tool/format for managing `menuconfig` we won't need to considerably change our codebase.

**Comment by GeneKong** [comment]
There are bugs in windows for default menuconfig, I cannot do anything for origin menuconfig in powershell in window 10.
For ESP-IDF please refer&nbsp;https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/kconfig.html


ESP-IDF uses&nbsp;kconfiglib&nbsp;which is a Python-based extension to the&nbsp;Kconfig&nbsp;system which provides a compile-time project configuration mechanism. Kconfig is based around options of several types: integer, string, boolean. Kconfig files specify dependencies between options, default values of the options, the way the options are grouped together, etc.


ESP IDF use kconfiglib for new version too.
I don't know think my port is very good, but if current framework wants to change menuconfig tool,&nbsp; maybe need more test.
If there's something need I do, I can help it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Valerii Koval"<notifications@github.com&gt;; 
发送时间: 2020年7月13日(星期一) 下午5:25
收件人: "platformio/platform-espressif32"<platform-espressif32@noreply.github.com&gt;; 
抄送: "以心之名"<gyx_edu@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [platformio/platform-espressif32] feat: Try to use kconfiglib to do menuconfig. (#374)





 
Hi @GeneKong ! Thanks for the PR. Could you please explain what are exactly the benefits of using kconfiglib directly? To minimize the chance of possible issues, we tend to use the same tools as the original framework as much as possible. In case when the maintainers of ESP-IDF decide to switch to a new tool/format for managing menuconfig we won't need to considerably change our codebase.

**Comment by valeros** [comment]
> ESP IDF use kconfiglib for new version too.

As you already know we delegate the task of running `menuconfig` tools to CMake, so how can I force that new kconfiglib?

**Comment by GeneKong** [comment]
After review esp-idf readme, maybe it's call idf menuconfig instead make menuconfig for use kconfiglib tools.
image

**Comment by GeneKong** [comment]
So it's possible for our framework keep two methods too.

**Comment by GeneKong** [comment]
Ok， I don’t have try for origin one, I will try origin SDK and give you response.





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Valerii Koval"<notifications@github.com&gt;; 
发送时间: 2020年7月13日(星期一) 下午5:52
收件人: "platformio/platform-espressif32"<platform-espressif32@noreply.github.com&gt;; 
抄送: "以心之名"<gyx_edu@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [platformio/platform-espressif32] feat: Try to use kconfiglib to do menuconfig. (#374)





  
ESP IDF use kconfiglib for new version too.
  
As you already know we delegate the task of running menuconfig tools to CMake, so how can I force that new kconfiglib?
 
&mdash;

**Comment by GeneKong** [comment]
Last time merge is failed, I use guiconfig for this python kconfig tool.
This pull has some other changes like:
1. Read sdkconfig flash size for partition;
2. in order to use main for src, default config will be empty.

**Comment by GeneKong** [comment]
@valeros 
```
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building ESP-IDF components for target esp32
-- Checking Python dependencies...
The following Python requirements are not satisfied:
gdbgui==0.13.2.0
pygdbmi<=0.9.0.2
reedsolo>=1.5.3,<=1.5.4
bitstring>=3.1.6
ecdsa>=0.16.0
Please follow the instructions found in the "Set up the tools" section of ESP-IDF Getting Started Guide
```
how to fixed this problem in ci?

**Comment by valeros** [comment]
All of that requirements are not required for build process, so it seems that you need to pass `-DPYTHON_DEPS_CHECKED=1` as well.

**Comment by GeneKong** [comment]
sorry for missing this options when merge.

**Pull request closed without merging**
