### PR TITLE
added new boards namino rosso / arancio

### PR DESCRIPTION
**Pull request by a-sapuppo**
Namino Boards: Namino combines the industrial world with the world of makers by making digital analog inputs, outputs and compatible Arduino shields available on the same board.

CPU: ESP32-S3-WROOM-1U-N4R8

```
NAMINO ROSSO provides the following input/output lines:
8 PNP digital inputs (up to 24Vdc)
1 knob input and button
8 PNP digital outputs (up to 24Vdc) of which 1 for stepper motor command with total current 200mA
1 SPDT relay output of 5A
8 single ended analog inputs (0-10V or 0-20mA) or 4 thermometric (NTC, PTC, PT1000) or 4 thermocouples (J, K, T) or 2 load cells, software configurable
1 analog output jumper configurable: 0-10V or 0-20mA
ARDUINO UNO compatible shield interface 


NAMINO ARANCIO provides the following input/output lines:
8 PNP digital inputs (up to 24Vdc)
1 knob input and button
8 PNP digital outputs (up to 24Vdc) of which 1 for stepper motor command with total current 200mA
1 SPDT relay output of 5A
4 analog inputs (0-10V or 0-20mA) software configurable
1 input for NTC (10kΩ) or board temperature reading
1 analog output jumper configurable: 0-10V or 0-20mA
ARDUINO UNO compatible shield interface 
```

### CODE REVIEW

**Comment by valeros** [comment]
Hi @a-sapuppo, thanks for the PR. In [this commit](https://github.com/espressif/arduino-esp32/commit/1f1a9ae4b58c27e3af059eb3a8832aa6132872f6) you disabled PSRAM by default. Shouldn't it be reflected in this PR as well? Also, do these boards require 1200bps touch? You didn't specify it in the manifests.

**Comment by a-sapuppo** [comment]
no good ?

**Comment by valeros** [comment]
> no good ?

PSRAM should be enabled or disabled by default?

**Comment by a-sapuppo** [comment]
disabled by default

**Comment by valeros** [comment]
Do these boards require 1200bps touch when uploading?

**Comment by a-sapuppo** [comment]
use_1200bps_touch added

**Comment by valeros** [comment]
OK, there are some other fixes required, it will be easier for me to add it by myself than ask you each time, but you need allow maintainers to edit the PR, see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by a-sapuppo** [comment]
write granted

**Comment by valeros** [comment]
Thanks, merged!

**Pull request merged**
