### PR TITLE
Simba framework for Nano32 board.

### PR DESCRIPTION
**Pull request by eerimoq**

### CODE REVIEW

**Comment by eerimoq** [comment]
The ESP32 part of Sibma is in a submodule to the main repository. Forgot to include the submodule in the release and that's the reason for the failed build. Will create a new release soon with the missing files.

**Comment by ivankravets** [comment]
Thanks Eric! Please ping me when all files will be ready. I'll merge.

**Comment by eerimoq** [comment]
The missing files are pushed and this pull request will hopefully work now. Thanks.

**Comment by eerimoq** [comment]
@ivankravets It's ready =)

**Comment by ivankravets** [comment]
Thanks! 😊

**Comment by eerimoq** [comment]
@ivankravets 

Simba is missing from the espressif32 platform page: http://platformio.org/platforms/espressif32

Anything I can help out fixing?

**Comment by ivankravets** [comment]
Thanks, fixed! 👍

**Comment by eerimoq** [comment]
=)

**Pull request merged**
