### PR TITLE
Create esp32-s3-devkitc-1-n8r8.json

### PR DESCRIPTION
**Pull request by mrfaptastic**
Create a working profile for the ESP32-S3-WROOM-1-N8R8, 8 MB QD, 8 MB OT PSRAM

### CODE REVIEW

**Comment by valeros** [comment]
Hi @mrfaptastic ! Please use the already available `esp32-s3-devkitc-1` and simply adjust the required hardware settings directly in your `platformio.ini`.

**Comment by mrfaptastic** [comment]
Can you advise on how to change the ` "memory_type":"qio_opi",` through a platformio.ini configuration file (refer to my proposed json for information)?

**Comment by Jason2866** [comment]
Here are some examples for providing setings in `platformio.ini` 

```
board_build.partitions=default_8MB.csv
board_build.f_cpu = 240000000L
board_build.arduino.memory_type = qio_opi
board_build.flash_freq=80m
board_build.flash_size =8MB
board_build.flash_mode = dio
board_build.boot=qio
board_build.flash_type = qio
board_build.psram_type = opi
board_build.memory_type = qio_opi
board_build.boot_freq = 80m
```

**Comment by mrfaptastic** [comment]
Thank you kindly @Jason2866!

**Pull request closed without merging**
