### PR TITLE
wrong flash mode resulting in issues

### PR DESCRIPTION
**Pull request by Jason2866**
issue https://github.com/espressif/arduino-esp32/issues/6572#issuecomment-1203630400
similar the fix for the S3 esp32-s3-devkitc-1.json

### CODE REVIEW

**Comment by Jason2866** [comment]
@valeros Probably a change for all newer boards to flash mode `qio` will avoid more issues here. Only old ESP32 board designs may not support mode `qio`.

**Comment by valeros** [comment]
Hi @Jason2866 ! Thanks for the PR. I'm in favor of keeping the flash mode settings in sync with the Arduino core for ESP32. For example, they use the `dio` mode for the `ESP32 Pico Kit` board https://github.com/espressif/arduino-esp32/blob/master/boards.txt#L1014:L1015. Is it a mistake?

**Comment by Jason2866** [comment]
Well, than the question is why `dio` works with Arduino IDE and it fails with PlatformIO?

**Comment by Jason2866** [comment]
Closing [this PR ](https://github.com/espressif/esp32-arduino-lib-builder/pull/80) will fix  the issues with flash modes. All modes are possible.

**Pull request closed without merging**
