### PR TITLE
Add new boards: Pycom LoPy & LoPy4

### PR DESCRIPTION
**Pull request by cyberman54**
corresponding PR in arduino-esp32 see [here](https://github.com/espressif/arduino-esp32/pull/1984)

### CODE REVIEW

**Comment by ivankravets** [comment]
Hey! Thank you so much for PR! ;)

These boards have the debugging pins and are ready for debugging using JTAG probe.
Please add data similar to https://github.com/platformio/platform-espressif32/blob/develop/boards/esp32dev.json

We need 
```
  "debug": {
    "openocd_board": "esp-wroom-32.cfg"
  },
```
and 
```
    "protocols": [
      "esptool",
      "esp-prog",
      "jlink",
      "olimex-arm-usb-tiny-h",
      "olimex-arm-usb-ocd-h",
      "olimex-arm-usb-ocd",
      "olimex-jtag-tiny",
      "iot-bus-jtag",
      "minimodule"
    ],
```

**Comment by cyberman54** [comment]
Added.

**Comment by ivankravets** [comment]
Thanks! Please ping me here when https://github.com/espressif/arduino-esp32/pull/1984 will be merged.

**Comment by cyberman54** [comment]
@ivankravets 

> Thanks! Please ping me here when [espressif/arduino-esp32#1984](https://github.com/espressif/arduino-esp32/pull/1984) will be merged.

Ping!
https://github.com/espressif/arduino-esp32/pull/1984#event-1975034815

**Comment by ivankravets** [comment]
@me-no-dev Do you have any plans for the next release of https://github.com/espressif/arduino-esp32?

**Comment by ivankravets** [comment]
Thanks!

**Pull request merged**
