### PR TITLE
Added --elf-sha256-offset to ElfToBin cmd for Arduino framework

### PR DESCRIPTION
**Pull request by paclema**
Bugfix for issue https://github.com/platformio/platform-espressif32/issues/972

### CODE REVIEW

**Comment by Jason2866** [comment]
Arduino IDE do not generate and use a SHA. Why should PlatformIO should behave here different?

**Comment by Jason2866** [comment]
@paclema I am not a maintainer nor a member of Platformio.
Just did a few PRs here. I maintain a fork of `platform-espressif32` for project [Tasmota](https://github.com/arendst/Tasmota)

**Comment by paclema** [comment]
@Jason2866 thanks a lot for your latest info! I have been testing the recent ESP-Insights now added into arduino-esp32 framework and also with the new way of generating the bootloader binary from the elf files.

I have enhanced the example that I mention in my previous post: [ESP-Insights with arduino-esp32 framework example](https://github.com/paclema/platformio_projects/tree/main/ESP_Insights) adding different board configurations and I have tested to debug it using an ESP-Prog (only debugging, uploading firmware using the board usb port) using this PR and using the default branch and I have the same successful results. 

With this PR I can store the elf hash (mandatory to use ESP-Insights platform) and I can still debug and change the flash freq and mode with esptool

Could you also run the example that I provide? It also prints using the serial some of the flash configurations and the app hash, so you can verify that it works well with any board flash configuration and this PR. As example:

```console
[     4][D][esp32-hal-cpu.c:244] setCpuFrequencyMhz(): PLL: 480 / 2 = 240 Mhz, APB: 80000000 Hz
[   451][I][esp32-hal-psram.c:96] psramInit(): PSRAM enabled
[   474][I][firmware_info.h:83] show_flash_info(): Chip out_id: 2113560
[   475][I][firmware_info.h:92] show_flash_info(): Chip unique out_id: 3676923104355062989
[   479][I][firmware_info.h:96] show_flash_info(): Flash mode: 00
[   486][I][firmware_info.h:97] show_flash_info(): CPU flash freq: 240 MHz, xTal: 40 MHz, APB: 80000000 Hz, Flash: 80000000 Hz
--+ Firmware info: +--
project_name: FirmwareNameTest
version: 1.2.3
time: 15:41:29+0100
date: 20 Dec 2022
idf_ver: v4.4.3
app_elf_sha256: 2ac5a7cbf44b14abf3254f3a7537a67e251bea1dd02b43040789c0a7cbc855df
[   664][I][firmware_info.h:25] print_sha256(): [shaELF] SHA-256 for current app running partition: : 9e971cffd23a51e3691d2f0ff24474e0c5abd4bfad2fca219d95d66a37f7ea07
```

On the other hand, I actually wonder now if adding this --elf-sha256-offset flag to ElfToBin cmd should be added here in this repo or into the [platformio-build.py](https://github.com/espressif/arduino-esp32/blob/master/tools/platformio-build.py) arduino-esp32 script... @me-no-dev what do you also know if adding this fix here would be better than adding it into arduino-esp32 build script?

**Comment by paclema** [comment]
Do you know what to do in this case @valeros? Thank you!

**Comment by Jason2866** [comment]
Yes, with the generating the bootloader out of the elf files, the problem with patching magic bytes needed with esptool.py is solved. I see no reason anymore for not implementing. Probably "cleaner" when done in Arduino code. Imho adding here is kind of patching.

**Comment by paclema** [comment]
@Jason2866 Sorry the example was in a private repo but you can find it now here:  [ESP-Insights with arduino-esp32 framework example](https://github.com/paclema/esp_insights_arduino_example/tree/master/ESP_Insights)

**Comment by paclema** [comment]
This is already merged into arduino-esp32 on https://github.com/espressif/arduino-esp32/pull/7566/files#diff-c910a41dbc9d05e6c71b19a2d6f9723ce36a566cbfa761e1fa195a68f99bb82cR247, therefore, this PR is not longer necessary.

**Pull request closed without merging**
