### PR TITLE
Add Espressif ESP32-C3-DevKitC-02

### LINKED ISSUE #641: Add board support for Espressif ESP32-C3-DevKitC-02
Espressif has a new C3 development board:  

https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/hw-reference/esp32c3/user-guide-devkitc-02.html

### PR DESCRIPTION
**Pull request by nkaaf**
- Add Board ESP32-C3-DevKitC-02
- Add "Bluetooth" connectivity to ESP32-DevKits

Should resolve #641

### CODE REVIEW

**Comment by valeros** [comment]
Hi @nkaaf ! Thanks for the PR. Have you tested this board with the latest platform?

**Comment by nkaaf** [comment]
> Hi @nkaaf ! Thanks for the PR. Have you tested this board with the latest platform? 

Hi @valeros , sorry for the delayed response. Is there any manual, on how I can test this locally on my computer? If so, I will do it :)

**Comment by nkaaf** [comment]
I have test the config with some example programs. All of them compile and run well 😁

**Comment by JurCag** [comment]
Hi @nkaaf, please have you tested BLE5 connectivity on this board, using ESP-IDF framework?

**Comment by Jason2866** [comment]
@JurCag  Will work as every other C3 board. The are all same.

**Comment by nkaaf** [comment]
Sorry for the late reply. Now I have test the Espressif-IDF example (https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/bluedroid/ble/ble_compatibility_test) on my ESP-C3 DevKit. It compiled without any problems and started the bluetooth device flawless. I was able to connect my smartphone with the device easily.

**Comment by craigvantonder** [comment]
@nkaaf I have been testing this out and it seems to be working fine. Thanks for your effort!

**Comment by nkaaf** [comment]
Is there anything left, that I have to do? :smiley:  @valeros

**Comment by valeros** [comment]
@nkaaf All good, thanks for the PR.

**Pull request merged**
