### PR TITLE
S3 Eye has 8MB OPI Flash

### PR DESCRIPTION
**Pull request by Jason2866**
as documented here https://www.espressif.com/en/news/Maple_Eye_ESP32-S3 fixes https://github.com/platformio/platform-espressif32/issues/1095

### CODE REVIEW

**Comment by hzhh110** [comment]
I use mac computer to write programs, I know the project of esp-who, and I can compile and run it, but it is too painful to write the project in it, without any code prompts, and then all kinds of error reports are red. Moreover, the arduino compiler doesn't have any code prompts, so I can't jump to the target function and file to check, so vscode + is used platformio + arduino development, other development boards are fine, basically work, but this esp32-s3-eye board can't be used

**Comment by hzhh110** [comment]
> as documented here https://www.espressif.com/en/news/Maple_Eye_ESP32-S3 fixes #1095

I use mac computer to write programs, I know the project of esp-who, and I can compile and run it, but it is too painful to write the project in it, without any code prompts, and then all kinds of error reports are red. Moreover, the arduino compiler doesn't have any code prompts, so I can't jump to the target function and file to check, so vscode + is used platformio + arduino development, other development boards are fine, basically work, but this esp32-s3-eye board can't be used

**Comment by hzhh110** [comment]
> as documented here https://www.espressif.com/en/news/Maple_Eye_ESP32-S3 fixes #1095

I use mac computer to write programs, I know the project of esp-who, and I can compile and run it, but it is too painful to write the project in it, without any code prompts, and then all kinds of error reports are red. Moreover, the arduino compiler doesn't have any code prompts, so I can't jump to the target function and file to check, so vscode + is used platformio + arduino development, other development boards are fine, basically work, but this esp32-s3-eye board can't be used

**Comment by valeros** [comment]
Thanks, merged!

**Comment by hzhh110** [comment]
> Thanks, merged!


I use the latest modified board information, but I still can't compile it successfully. I use @ 6.2 version and @ 5.2 version. The way of arduino is crashed, and I can't succeed



for :
esp32s3camlcd.json

{
"build": {
"arduino":{
"ldscript": "esp32_out.ld",
"memory_type": "opi_opi"
},
"boot": "opi",
"core": "esp32",
"extra_flags": [
"-DARDUINO_RUNNING_CORE=1",
"-DARDUINO_EVENT_RUNNING_CORE=1",
"-DBOARD_HAS_PSRAM",
"-DARDUINO_ESP32S3_CAM_LCD",
"-DARDUINO_USB_MODE=1"
],
"f_cpu": "240000000L",
"f_flash": "80000000L",
"flash_mode": "dout",
"hwids": [
[
"0X303A",
"0x1001"
]
],
"mcu": "esp32s3",
"variant": "esp32s3camlcd"
},
"connectivity": [
"wifi",
"bluetooth"
],
"debug": {
"openocd_target": "esp32s3.cfg"
},
"frameworks": [
"arduino",
"espidf"
],
"name": "ESP32S3 CAM LCD",
"upload": {
"flash_size": "8MB",
"maximum_ram_size": 327680,
"maximum_size": 8388608,
"require_upload_port": true,
"speed": 921600
},
"url": "https://www.espressif.com/en/news/Maple_Eye_ESP32-S3",
"vendor": "Espressif"
}

**Pull request merged**
