### PR TITLE
Create LionBitS3 Json for Lion:Bit S3 Device 

### PR DESCRIPTION
**Pull request by PradeepKotu**
Create LionBitS3 Json

### CODE REVIEW

**Comment by PradeepKotu** [comment]
@ivankravets please see if there is any issue

**Comment by valeros** [comment]
Hi @PradeepKotu, your PR will be merged once a new release of Arduino core with proper variant file is published.

**Comment by PradeepKotu** [comment]
@valeros can we merge it now

**Comment by valeros** [comment]
Thanks for the PR, merged!

**Pull request merged**
