### PR TITLE
heltec_wireless_stick_lite: Add board definition

### PR DESCRIPTION
**Pull request by aparcar**
Add board defitintion for Heltecs Wireless Stick Lite.
Product: https://heltec.org/project/wireless-stick-lite/

The patch is based on @brunohorta82 previous work.

### CODE REVIEW

**Comment by aparcar** [comment]
@Heltec-Aaron-Lee please have a look

**Comment by Heltec-Aaron-Lee** [comment]
@aparcar Thanks for your feedback. I will look into this.

**Comment by aparcar** [comment]
I tested it with some basic LoRa functionality and it works fineso far

**Comment by brunohorta82** [comment]
i tested and works fine

**Comment by valeros** [comment]
Hi @aparcar ! Thanks for the PR! Am missing something or there is no official support for this board here https://github.com/espressif/arduino-esp32/tree/master/variants ?

**Comment by aparcar** [comment]
@valeros I created there a PR as well https://github.com/espressif/arduino-esp32/pull/3925

**Pull request closed without merging**
