### PR TITLE
Add board definitions for M5Station

### PR DESCRIPTION
**Pull request by Tinyu-Zhao**
The link to this development version is here.
[M5Station-485](https://docs.m5stack.com/en/core/station_485)
[M5Station-BAT](https://docs.m5stack.com/en/core/station_bat)

### CODE REVIEW

**Comment by valeros** [comment]
Hi @Tinyu-Zhao , thanks for the PR! There is no such variant `m5stack_station` in the official Arduino core for ESP32 https://github.com/espressif/arduino-esp32/tree/master/variants. Please add this board there in the first place.

**Comment by Tinyu-Zhao** [comment]
OK, I have added the relevant documents and are waiting for the review of espressif, Thank you.

**Comment by Tinyu-Zhao** [comment]
Hello, at the moment espressif has merged the request, please help with this.https://github.com/espressif/arduino-esp32/pull/7101

**Comment by valeros** [comment]
Thanks, merged!

**Pull request merged**
