### PR TITLE
Add SparkFun ESP32 MicroMod

### PR DESCRIPTION
**Pull request by seanhagen**
Add the JSON configuration for the [SparkFun ESP32 MicroMod](https://www.sparkfun.com/products/16781)

### CODE REVIEW

**Comment by seanhagen** [comment]
I did my best to translate the info from the boards.txt using the 1.0.1 tarball downloaded from the [url in the SparkFun board manager JSON file](https://raw.githubusercontent.com/sparkfun/Arduino_Boards/main/IDE_Board_Manager/package_sparkfun_index.json), but I'm not 100% certain I got it right, so I'm attaching the esp32micromod section of the boards.txt here: 
[micromod.txt](https://github.com/platformio/platform-espressif32/files/6994448/micromod.txt)

**Comment by valeros** [comment]
Hi @seanhagen ! Thanks for the PR! Currently we only support the official Arduino ESP32 core from https://github.com/espressif/arduino-esp32, so it might be a good idea to submit a PR with this new variant to that repository so it will land in the upcoming v2.0.

**Comment by seanhagen** [comment]
@valeros is that the repository that pio downloads to `~/.platformio/packages/framework-arduinoespressif32` ? Cause if it is I've been looking for that repo so I could add the variant!

**Comment by seanhagen** [comment]
Opened a [PR](https://github.com/espressif/arduino-esp32/pull/5556) to add the ESP32 MicroMod to the espressif/arduion-esp32 repo!

**Comment by valeros** [comment]
> is that the repository that pio downloads to ~/.platformio/packages/framework-arduinoespressif32 ?

That's right, PlatformIO uses the latest stable v1.0.6

**Comment by seanhagen** [comment]
So if the PR I opened in the espressif/arduion-esp32 repo is merged, is this one still required or is there some tooling or scripts that will automagically generate the `esp32micromod.json` file from that repo?

**Comment by valeros** [comment]
Most of the board manifests are handled manually.

**Comment by seanhagen** [comment]
Just waiting on the maintainers of the `espressif/arduino-esp32` to either merge the PR I've got open there or to let me know if it needs any more work, I'll update here when that PR is merged in.

**Comment by seanhagen** [comment]
The `espressif/arduino-esp32` [PR that adds the MicroMod](https://github.com/espressif/arduino-esp32/pull/5556) is merged! Looks like it's gonna be in v2 :smile:

**Comment by michaelcdillon** [comment]
Thanks @seanhagen for putting in this board request, and doing the leg work in the [PR that adds the MicroMod](https://github.com/espressif/arduino-esp32/pull/5556)!

I'm also looking to use this board, so is there anything here I can do to help get this merged in? 

I added the board manually, but I'm getting a missing `pins_arudino.h` error, which suggests that the framework isn't pulling the latest stable version of `arduino-esp32`. I've tried to force update the framework by removing it and reinstalling, but the version downloaded doesn't have the changes @seanhagen put in to that repo. 

Its not clear to me what drives what version of that repo is included with this framework, so any help in overriding this would be helpful to me while we wait on the official inclusion of this board.

**Comment by valeros** [comment]
Many thanks!

**Pull request merged**
