### PR TITLE
Support for esp8684 (esp32-c2) 

### PR DESCRIPTION
**Pull request by Jason2866**
MCU is supported since IDF 5.0

### CODE REVIEW

**Comment by lboue** [comment]
Can you merge this PR to add support for esp8684 (esp32-c2)?

**Comment by lboue** [comment]
Any news ?

**Comment by Jason2866** [comment]
@valeros Planned to merge, anytime soon? If not i will close.

**Comment by olemmela** [comment]
@Jason2866  should these commits be cleaned up a bit before merging? Combining them into one or two commits would make the git history log look better.

**Comment by Jason2866** [comment]
@olemmela No need, there is the squash merge command.

**Comment by pkendall64** [comment]
[ExpressLRS](https://expresslrs.org) would also love to have support for the C2 to replace the aging ESP8285 that is used on the smaller receivers.

**Comment by ceifa** [comment]
@valeros any reason to not merge this?

**Comment by Jason2866** [comment]
@ivankravets  Is there a reason for not merging this PR? The C6 is supported, why not the C2? It is a bug fixing PR since Platformio claims to support IDF 5.1. The C2 IS supported in IDF 5.1.

**Comment by richrd** [comment]
Any news on this? Would be great if this was merged, unless there are any blockers of course.

**Comment by acvigue** [comment]
+1 for this.

**Comment by Jason2866** [comment]
@Maitham-idea This PR adds the missing C2 support with IDF. It does NOT add the possibility to use the C2 with Arduino framework.

**Comment by felipecrs** [comment]
Why was this closed?

**Pull request closed without merging**
