### PR TITLE
Added board ESP32-PICO-DevKitM-2.

### PR DESCRIPTION
**Pull request by djpearman**
Hi,

Added board definition file for [ESP32-PICO-DevKitM-2](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/hw-reference/esp32/get-started-pico-devkitm-2.html).

Best regards,
djpearman

### CODE REVIEW

**Comment by valeros** [comment]
Hi @djpearman, thanks for the PR. Aren't `-mfix-esp32-psram-cache-issue` and `-mfix-esp32-psram-cache-strategy=memw` flags required for proper PSRAM support on ESP32?

**Comment by Jason2866** [comment]
@valeros The options are only needed for early esp32 board (to be exact rev 0 and 1)
Since the pico variant is a later rev. it is not needed.

**Comment by djpearman** [comment]
Hi @valeros,

I had those two flags in there initially, but came across [a comment](https://github.com/platformio/platform-espressif32/issues/947#issuecomment-1295306307) stating that the PICO-V3-02 no longer requires them. Removed them, tested it and it works. ESP.getPsramSize() and ESP.getFreePsram() report values, so I figure it works.

**Comment by valeros** [comment]
Many thanks, merged!

**Pull request merged**
